package com.manish.LLD.CoupounSystem.Type2.context;

import com.manish.LLD.CoupounSystem.Type2.model.PaymentMethod;
import com.manish.LLD.CoupounSystem.Type2.model.UserContext;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class OrderContext {
    private UserContext userContext;
    private ProductContext productContext;
    private double orderAmount;
    private PaymentMethod paymentMethod;
    private String deliveryType;
    private boolean isFirstOrder;
    private String orderId;
    private String promoCode;

    // Constructor
    public OrderContext(UserContext userContext,
                        ProductContext productContext,
                        double orderAmount,
                        PaymentMethod paymentMethod) {
        this.userContext = userContext;
        this.productContext = productContext;
        this.orderAmount = orderAmount;
        this.paymentMethod = paymentMethod;
    }

    // Additional constructors
    public OrderContext(UserContext userContext,
                        ProductContext productContext,
                        double orderAmount,
                        PaymentMethod paymentMethod,
                        String deliveryType,
                        boolean isFirstOrder) {
        this(userContext, productContext, orderAmount, paymentMethod);
        this.deliveryType = deliveryType;
        this.isFirstOrder = isFirstOrder;
    }

    // Helper methods
    public boolean isCashOnDelivery() {
        return paymentMethod == PaymentMethod.CASH_ON_DELIVERY;
    }

    public boolean isUsingWallet() {
        return paymentMethod == PaymentMethod.WALLET;
    }

    public boolean isExpressDelivery() {
        return "express".equalsIgnoreCase(deliveryType);
    }

    public double getDiscountedOrderAmount(double discountPercentage) {
        return orderAmount * (1 - discountPercentage / 100);
    }

    // Getters (generated by Lombok)
    // Setters (generated by Lombok)
}